kreuzwerker/terraform-provider-docker

- .github/workflows/website.yaml
- .markdownlinkcheck.json
- .markdownlint.yml
- GNUmakefile
Close #12 
* Remove existing broken tests
* Test website with [gaurav-nelson/github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check) and [markdown-lint](https://github.com/avto-dev/markdown-lint)
> ci: fix website ci

- .github/workflows/golangci-lint.yaml
- .golangci.yml
- docker/config.go
- docker/data_source_docker_network.go
- docker/resource_docker_container_funcs.go
- docker/resource_docker_container_migrate.go
- docker/resource_docker_container_test.go
- docker/resource_docker_image_funcs.go
- docker/resource_docker_image_test.go
- docker/resource_docker_network.go
- docker/resource_docker_network_funcs.go
- docker/resource_docker_network_test.go
- docker/resource_docker_registry_image_funcs.go
- docker/resource_docker_service_funcs.go
- docker/resource_docker_service_test.go
- docker/resource_docker_volume_test.go
- docker/structures_service.go
- docker/validators.go
Close #13 
- refactor: fix code with golangci-lint
- ci: configure golangci-lint
> introduce golangci-lint

- docker/resource_docker_service.go
- docker/resource_docker_service_funcs.go
- docker/resource_docker_service_test.go
- docker/structures_service.go
- website/docs/r/service.html.markdown
> feat: support max replicas of Docker Service Task Spec

- README.md
Fix Github repository from deprecated to the new one
> Fix Github repository URL in README

- website/docs/r/image.html.markdown
> docs: add an example to build an image with docker_image

- .github/workflows/stale.yaml
Close #155 
Configure https://github.com/actions/stale
> chore: configure actions/stale

- internal/provider/resource_docker_container_migrators.go
> fix: assign map to rawState when it is nil to prevent panic

- internal/provider/resource_docker_container_funcs.go
- internal/provider/resource_docker_container_structures.go
- internal/provider/resource_docker_service_structures.go
> fix: add service host flattener with space split

- CONTRIBUTING.md
- templates/resources/image.md.tmpl
> docs: fix few typos

- docs/resources/registry_image.md
- examples/resources/docker_registry_image/resource.tf
- internal/provider/resource_docker_registry_image.go
> docs: update to absolute path for registry image contrext folder

- docs/resources/container.md
- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_container_funcs.go
- internal/provider/resource_docker_container_test.go
- testdata/resources/docker_container/testAccDockerContainerCustomizedConfig.tf
> feat: add container storage opts

- docs/resources/registry_image.md
- go.mod
- go.sum
- internal/provider/resource_docker_registry_image.go
> Fixed typo

- README.md
- docs/resources/container.md
- docs/resources/registry_image.md
- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_container_funcs.go
- internal/provider/resource_docker_container_test.go
- internal/provider/resource_docker_registry_image.go
- templates/resources/registry_image.md.tmpl
- see #81
- fixed tests and tested with a [real build](https://github.com/kreuzwerker/terraform-provider-docker/blob/master/CONTRIBUTING.md#test-against-current-terraform-iac-descriptions) of the provider
- added `Stargazers over time`
> fix: pass container rm flag

- CHANGELOG.md
- docs/index.md
- internal/provider/config.go
- internal/provider/provider.go
In place of #301 
Resolves #29
> feat: add parameter for SSH options

- internal/provider/data_source_docker_image.go
- internal/provider/data_source_docker_image_test.go
- internal/provider/resource_docker_image_funcs.go
This is based on https://github.com/kreuzwerker/terraform-provider-docker/pull/404
(I want to release a new patch version today)
> fix: Improve searchLocalImages error handling.

- internal/provider/data_source_docker_registry_image.go
> fix: Docker Registry Image data source use HEAD request to query image digest

- docs/resources/image.md
- internal/provider/resource_docker_image.go
- internal/provider/resource_docker_image_funcs.go
Fixes #443 and enhances documentation.
> feat: Add image_id attribute to docker_image resource.

- docs/index.md
- internal/provider/provider.go
- internal/provider/provider_test.go
- scripts/testacc_cleanup.sh
- scripts/testacc_setup.sh
- testdata/resources/provider/testAccDockerProviderDisabledRegistryAuth.tf
Fixes #470 
Supersedes the previous PR https://github.com/kreuzwerker/terraform-provider-docker/pull/493
> feat: Support registries with disabled auth

- docs/resources/container.md
- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_container_funcs.go
> feat: cgroupns support

- docs/index.md
- templates/index.md.tmpl
> docs: Add documentation of remote hosts.

- docs/resources/service.md
- internal/provider/resource_docker_service.go
- internal/provider/resource_docker_service_structures.go
> feat: Add sysctl implementation.

- internal/provider/resource_docker_container_funcs.go
> fix: Access health of container correctly.

- internal/provider/resource_docker_registry_image_funcs.go
> fix: Implement proxy support.

- .github/workflows/release.yaml
- CHANGELOG.md
- GNUmakefile
- README.md
- docs/index.md
- examples/provider/provider-tf12.tf
- examples/provider/provider-tf13.tf
Simple fixes for the release process as it currently is broken (see https://github.com/kreuzwerker/terraform-provider-docker/actions/runs/14455637591/job/40538149528)
> Chore: Prepare release 3.1.1

- internal/provider/authentication_helpers.go
- internal/provider/authentication_helpers_test.go
- internal/provider/data_source_docker_registry_image.go
- internal/provider/resource_docker_registry_image_funcs.go
Originally proposed by @achille-roussel in https://github.com/kreuzwerker/terraform-provider-docker/pull/666
> fix: Authentication to ECR public

- docs/resources/container.md
- docs/resources/image.md
- examples/resources/docker_image/resource-build-triggers.tf
- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_image.go
- templates/resources/image.md.tmpl
In order to get things merged faster - this PR contains all the changes from the following PRs:
https://github.com/kreuzwerker/terraform-provider-docker/pull/576 @triggerNZ
https://github.com/kreuzwerker/terraform-provider-docker/pull/536 @Tyonar
https://github.com/kreuzwerker/terraform-provider-docker/pull/539 @matthew-palmer
https://github.com/kreuzwerker/terraform-provider-docker/pull/541 @siddharthab
https://github.com/kreuzwerker/terraform-provider-docker/pull/546 @akeamc
https://github.com/kreuzwerker/terraform-provider-docker/pull/549 @manju-rn
https://github.com/kreuzwerker/terraform-provider-docker/pull/665 @tparikka
https://github.com/kreuzwerker/terraform-provider-docker/pull/559 @tk3fftk
Thanks to everyone for their proposed changes!
> docs: Consolidated update of docs from several PRs

- docs/resources/image.md
- internal/provider/resource_docker_image.go
- internal/provider/resource_docker_image_test.go
- templates/resources/image.md.tmpl
- testdata/resources/docker_image/testCreateDockerImageCreateTimeout.tf
Many thanks to @voroninman and his PR #343
Fixes #254
> feat: Implement docker_image timeouts

- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_container_funcs.go
- internal/provider/resource_docker_container_test.go
- testdata/resources/docker_container/testAccDockerContainerUploadConfigPermissions.tf
> feat: Implement upload permissions in docker_container resource

- internal/provider/data_source_docker_image.go
- internal/provider/resource_docker_container_structures.go
- internal/provider/resource_docker_image_funcs.go
fixes #551 
And also remove DEBUG outputs which are just unecessary
> fix: Store correctly ports from server

- docs/resources/registry_image.md
- internal/provider/resource_docker_registry_image.go
- internal/provider/resource_docker_registry_image_funcs.go
- internal/provider/resource_docker_registry_image_test.go
- testdata/resources/docker_registry_image/testBuildDockerRegistryImageWithAuthConfig.tf
> feat: Implement auth_config for docker_registry_image

- docs/resources/tag.md
- internal/provider/resource_docker_tag.go
> feat: Implement tag triggers for docker_tag resource

- docs/index.md
- internal/provider/data_source_docker_registry_image_test.go
- internal/provider/provider.go
- templates/index.md.tmpl
- testdata/data-sources/docker_registry_image/testAccDockerImageDataSource_WithoutDaemon.tf
> feat: disable_docker_daemon_check for provider

- docs/index.md
- internal/provider/provider.go
- internal/provider/provider_test.go
> feat: Implement support for docker context

- internal/provider/resource_docker_registry_image_funcs.go
> fix: Use auth_config block also for registry_image delete functionality

- docs/resources/container.md
- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_container_funcs.go
- internal/provider/resource_docker_container_structures.go
> feat: Implement volume_options subpath

- docs/resources/container.md
- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_container_funcs.go
- internal/provider/resource_docker_container_test.go
- testdata/resources/docker_container/testAccDockerContainerimageId.tf
> fix: Prevent recreation of image name is intentionally set to a fixed value

- docs/resources/container.md
- internal/provider/resource_docker_container.go
- internal/provider/resource_docker_container_funcs.go
> feat: Implement healthcheck start interval

- internal/provider/provider.go
> fix: Make endpoint validation less strict

- docs/data-sources/registry_image.md
- internal/provider/data_source_docker_registry_image.go
- internal/provider/data_source_docker_registry_image_test.go
- internal/provider/resource_docker_image_funcs.go
- testdata/data-sources/docker_registry_image/testAccDockerImageDataSourceConfig.tf
> feat: Allow digest in image name

- internal/provider/resource_docker_container_funcs.go
> fix: Typo in cgroup_parent handling

- docs/resources/image.md
- docs/resources/registry_image.md
- internal/provider/docker_buildx_build.go
- internal/provider/helpers.go
- internal/provider/resource_docker_image.go
- internal/provider/resource_docker_image_test.go
- internal/provider/resource_docker_registry_image_funcs.go
- testdata/resources/docker_image/testAccDockerImageCacheFromCacheTo.tf
> feat: Implement cache_from and cache_to for docker_image

- internal/provider/resource_docker_container_funcs.go
> fix(container): omit sending systempaths=unconfined to daemon

- docs/resources/image.md
- internal/provider/docker_buildx_build.go
- internal/provider/resource_docker_image.go
- internal/provider/resource_docker_image_test.go
- testdata/resources/docker_image/testAccDockerImageAdditionalContexts.tf
> feat: Add build option for additional contexts
