docker/resource_docker_network_funcs.go
@mavogel fixes #7 
I'm not completely sure about this so... PTAL and let me know if this is the right approach.
=> Fix aux_address crash

.github/workflows/acc-test.yaml, .github/workflows/compile.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/release.yml, .github/workflows/unit-test.yaml, .github/workflows/website.yaml
- implements #5 
- adds `ubuntu:20.04` as image for all workflows
- bumps docker version to `20.10.1`
=> ci: update ubuntu images and docker version

docker/resource_docker_image.go, docker/resource_docker_image_funcs.go, docker/resource_docker_image_test.go, website/docs/r/image.html.markdown
* feat: add an option `force_remove` to docker_image
* fix: remove a Docker image by not image id but image name
=> feat: add force_remove option to r/image

website/docs/r/service.html.markdown
https://github.com/kreuzwerker/terraform-provider-docker/issues/103#issuecomment-752055852
=> docs: add labels to arguments of docker_service

docker/resource_docker_image_funcs.go
Close #116 
https://github.com/kreuzwerker/terraform-provider-docker/blob/5f2ed87b8ff668445738f2c9992cb1e6b08532ff/docker/resource_docker_registry_image_funcs.go#L457
When `pullOpts.Tag` is empty, `FqName` is invalid format `%s/%s:`.
```
$ terraform version
Terraform v0.13.5
+ provider registry.terraform.io/kreuzwerker/docker v2.9.0
```
```tf
resource "docker_registry_image" "eshopwebmvc" {
name = "suzukishunsuke/test"
build {
context = "."
}
}
```
Dockerfile
```dockerfile
FROM alpine:3.11.6
```
```
$ terraform apply
```
```
Error: Error building docker image: Error response from daemon: invalid reference format
```
<details>
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following …
```
=> fix: set "latest" tag when tag isn't specified

docker/data_source_docker_plugin.go, docker/data_source_docker_plugin_test.go, docker/provider.go, docker/resource_docker_container.go, docker/resource_docker_container_v1.go, docker/resource_docker_plugin.go, docker/resource_docker_plugin_funcs.go, docker/resource_docker_plugin_test.go, docker/resource_docker_service.go, go.mod, website/docs/d/plugin.html.markdown, website/docs/r/image.html.markdown, website/docs/r/plugin.html.markdown
=> feat: support Docker plugin

docker/resource_docker_container_test.go, docker/resource_docker_image_test.go, docker/resource_docker_service_test.go, website/docs/d/registry_image.html.markdown, website/docs/index.html.markdown, website/docs/r/config.html.markdown, website/docs/r/container.html.markdown, website/docs/r/image.html.markdown, website/docs/r/secret.html.markdown, website/docs/r/service.html.markdown
> Warning: Interpolation-only expressions are deprecated
>
> Terraform 0.11 and earlier required all non-constant expressions to be
> provided via interpolation syntax, but this pattern is now deprecated. To
> silence this warning, remove the "${ sequence from the start and the }"
> sequence from the end of this expression, leaving just the inner expression.
>
> Template interpolation syntax is still used to construct strings from
> expressions when the template includes multiple interpolation sequences or a
> mixture of literal strings and interpolations. This deprecation applies only
> to templates that consist entirely of a single interpolation sequence.
We requires `Terraform >=0.12.x`, so we should fix legacy configuraiton style. …
=> docs: fix legacy configuration style

.github/ISSUE_TEMPLATE/Bug_Report.md
Sometimes there are bug reports which we can't reproduce the problem.
By adding the guide to write good bug report, we want to solve this problem.
=> chore: add the guide about Terraform Configuration in Bug Report

CONTRIBUTING.md
When `Terraform Configuration Files` in a bug report isn't good, it's useful to quote `Guide of Bug report`.
=> docs: add a guide about writing issues to CONTRIBUTING.md

internal/provider/resource_docker_image_funcs.go, internal/provider/resource_docker_image_test.go
https://github.com/kreuzwerker/terraform-provider-docker/issues/52#issuecomment-806581094 
9efd1265f0823289c65e7633f02996b01034d8c1
https://github.com/kreuzwerker/terraform-provider-docker/pull/151/checks?check_run_id=2197760165#step:16:537
```
=== RUN   TestAccDockerImage_tag_sha265
resource_docker_image_test.go:246: Step 1/1 error: Error running apply: exit status 1
2021/03/25 23:30:38 [DEBUG] Using modified User-Agent: Terraform/0.12.30 HashiCorp-terraform-exec/0.13.0
Error: Unable to read Docker image into resource: Unable to find or pull image nginx:1.18.0-alpine@sha256:0c56c40f232f41c1b8341c3cc055c8b528cb6decefd7f7c8506e2d30bb9678b6
on terraform_plugin_test.tf line 2, in resource "docker_image" "nginx":
2: resource "docker_image" "nginx" {
--- FAIL: TestAccDockerImage_tag_sha265 …
```
=> fix: search local images with Docker image ID

renovate.json5
https://docs.renovatebot.com/configuration-options/
To use Renovate, we have to install GitHub App. https://github.com/apps/renovate
https://dependabot.com/
I don't have a strong opinion, but I usually use Renovate for both personal OSS and job.
I'm not familiar with Dependabot.
=> chore(renovate): update dependencies automatically by Renovate

templates/resources/image.md.tmpl
=> docs: fix typos in docker_image example usage

docs/resources/registry_image.md, internal/provider/resource_docker_registry_image.go
Fixes #268
Doc was truncated during docs migration. This PR restores original line from https://github.com/kreuzwerker/terraform-provider-docker/blob/96a6a8dbee96b0b24946bda22e4fd612fe613cb4/website/docs/r/registry_image.html.markdown?plain=1#L71 
Happy Hacktoberfest!
=> docs: fix r/registry_image truncated docs

docs/index.md, docs/resources/service.md, examples/provider/provider-ssh.tf, examples/resources/docker_service/resource-advanced.tf, go.mod, go.sum, internal/provider/provider.go, internal/provider/resource_docker_service.go
and additionally
- fixes website docs of #335 
- beautifies the service docs
- replace markdown-cli image due to the [hint](https://gitlab.com/06kellyjac/docker_markdownlint-cli#how-to-use-this-image). Note: had to build it locally for my M1 and added a [PR](https://gitlab.com/06kellyjac/docker_markdownlint-cli/-/merge_requests/4)
=> docs: fix service options

.github/workflows/acc-test.yaml, renovate.json5
This fixes two things:
- Increasing the timeout of the github actions to 15 min, as the last runs always timed out (https://github.com/kreuzwerker/terraform-provider-docker/actions/runs/2514887891)
- Adding `testdata` folder to renovate ignorePath, we don't need renovate PRs for the docker versions used there.
=> fix(ci): Pipeline updates

internal/provider/resource_docker_image_funcs.go, internal/provider/resource_docker_image_test.go, internal/provider/resource_docker_registry_image_funcs.go, internal/provider/resource_docker_registry_image_test.go, testdata/resources/docker_image/testDockerImageDockerfileOutsideContext.tf, testdata/resources/docker_registry_image/testDockerRegistryImageDockerfileOutsideContext.tf
This aligns the implementation with the offical `docker build` command. Users are now able to specify `Dockerfiles` which are outside the build context.
Upstream file: https://github.com/docker/cli/blob/master/cli/command/image/build.go#L229
This shoud not break anything :)
Fixes #401
=> fix: Enables having a Dockerfile outside the context

GNUmakefile, internal/provider/authentication_helpers.go, internal/provider/authentication_helpers_test.go, internal/provider/data_source_docker_registry_image.go, internal/provider/provider.go
This fixes https://github.com/kreuzwerker/terraform-provider-docker/issues/356
When looking at the code I noticed that for some registry functionality we need the HTTP authentication and for some registry functionality we need the docker authentication (https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html). I found that the two authentication mechanisms from related and can be converted to the other one.
I used that to write a conversion function. Now it does not matter which value you pass to the provider, it should always work.
In a different PR I am also planning on adding tests for the different registries (github, ecr, gitlab, gcloud...)
This PR also adds two new makefile targets to build and install the provider locally.
=> fix: ECR authentication

.github/workflows/compile.yaml
You cannot use both `paths` and `paths-ignore` at the same time.
=> fix: Fix compile.yaml workflow.

internal/provider/validators.go
Included support for Absolute Paths in Windows that begin with e.g. `G:/`
Tests performed also with an online RegEx checker: regexr.com/6s741
=> Adding Support for Windows Paths in Bash

internal/provider/authentication_helpers.go, internal/provider/data_source_docker_registry_image.go, internal/provider/resource_docker_config_test.go, internal/provider/resource_docker_container_test.go, internal/provider/resource_docker_registry_image_funcs.go, internal/provider/resource_docker_secret_test.go, internal/provider/resource_docker_service_funcs.go, internal/provider/resource_docker_service_structures.go, internal/provider/test_helpers.go
This adds support for authorization with Azure Container Registry.
Previously this would fail for 2 reasons:
1. It was trying to use basic for azurecr
2. It was not looking for the `access_token` in the oauth response
=> fix: oauth authorization support for azurecr

main.go
This fixes the following error that shows up if you run the provider in debug mode:
```json
{
"@level": "info",
"@message": "2022/09/21 15:25:08 [ERROR] Error parsing provider name \"registry.terraform.io/kreuzwerker/terraform-provider-docker\": Invalid provider type: Provider source \"kreuzwerker/terraform-provider-docker\" has a type with the prefix \"terraform-provider-\", which isn't valid. Although that prefix is often used in the names of version control repositories for Terraform providers, provider source strings should not include it.\n\nDid you mean \"kreuzwerker/docker\"?",
"@timestamp": "2022-09-21T15:25:08.353718-04:00"
}
```
=> fix: Correct provider name to match the public registry

docs/resources/container.md, internal/provider/resource_docker_container.go, internal/provider/resource_docker_container_funcs.go, internal/provider/resource_docker_container_test.go
This feature adds the ability to check and wait for the container healthy state at creation.
Two options are added to the `docker_container`resource:
- `wait` : flag to wait for the healthy state at creation (default `false`)
- `wait_timeout`: the maximal timeout in seconds to wait for (default `60`)
The `wait` option is disabled by default as a `healthcheck` block is required to successfully create the resource. It works too with the `count` option but all containers will be started and checked at the same time for the given resource.
Note that the healthy state is only checked at resource creation not afterwards.
Here is an example:
```
resource "docker_network" "test" {
name = "test"
}
resource "docker_image" "nginx" {
name = "bhuisgen/alpine-nginx:prod"
}
resource "docker_container" …
```
=> feat: support docker container healthy state

GNUmakefile
my env
```zsh
$ go env GOHOSTOS
darwin
$ go env GOHOSTARCH
amd64
```
=> fix: Set `OS_ARCH` from `GOHOSTOS` and `GOHOSTARCH`

internal/provider/data_source_docker_registry_image.go
As reported in #481, there is an issue with handling auth headers with more than one scope. For example
```
header := "Bearer realm="https://gcr.io/v2/token",service="gcr.io",scope="repository:<owner>/:<repo>/<name>:pull””
```
Works fine with single scopes. However, once we have more than one scope like
```
header := "Bearer realm="https://gcr.io/v2/token",service="gcr.io",scope="repository:<owner>/:<repo>/<name>:push,pull""
```
https://github.com/kreuzwerker/terraform-provider-docker/blob/ffb0cbfb75f5fc331777e33c6eab6c476b9e88cf/internal/provider/data_source_docker_registry_image.go#L156
Essentially returns a trailing map value of ["pull"] which breaks on https://github.com/kreuzwerker/terraform-provider-docker/blob/ffb0cbfb75f5fc331777e33c6eab6c476b9e88cf/internal/provider/data_source_do …
=> fix: Handle Auth Header Scopes

docs/resources/registry_image.md, internal/provider/resource_docker_registry_image.go
=> feat: Add triggers attribute to docker_registry_image

docs/resources/image.md, internal/provider/resource_docker_container_funcs.go, internal/provider/resource_docker_image.go, internal/provider/resource_docker_image_funcs.go, internal/provider/resource_docker_image_test.go, testdata/resources/docker_image/testAccDockerImagePlatform.tf
Implements support for specifying the platform when pulling an image.
Closes #476
=> feat: Add platform attribute to docker_image resource

docs/resources/container.md, internal/provider/resource_docker_container.go, internal/provider/resource_docker_container_migrators.go, internal/provider/resource_docker_container_structures.go, internal/provider/resource_docker_container_test.go
Add the container MAC address for each network into state, so it can be referenced if needed.
I didn't feel this needed a dedicated test case, so I just added a check on an existing one. Please let me know if you feel otherwise.
=> feat(container): add MAC address to state

internal/provider/resource_docker_container.go, internal/provider/resource_docker_image_test.go, testdata/data-sources/docker_registry_image/testAccDockerImageDataSourcePrivateConfig.tf, testdata/resources/docker_container/testAccDockerContainerNetworksDualStackAddressConfig.tf, testdata/resources/docker_image/testAddDockerPrivateImageConfig.tf
Just trying to fix tests and get everything running again. Default docker networking has changed with newer docker server version. I am also thinking of adding tests to test against different docker server versions, e.g. via a matrix as we do with terraform
=> fix: Set correct default network driver and fix a test

docs/resources/container.md, internal/provider/resource_docker_container.go, internal/provider/resource_docker_container_funcs.go
=> feat: support setting cpu shares

docs/resources/image.md, go.mod, go.sum, internal/provider/resource_docker_image.go, internal/provider/resource_docker_image_funcs.go, internal/provider/resource_docker_image_test.go, testdata/resources/docker_image/testDockerImageBuildSecrets.tf
Enables passing of build-secrets through the 'secrets' block inside 'build'.
The feature is only available when using Buildkit.
I don't have much knowledge as to how build secrets work, but I tried to follow how buildx does it and implement it here. This feature is something that pops up as a need often at my job.
If changes need to be made, I will try to accommodate. :) 
Tested by installing the provider locally, pushing the secrets into files in the Dockerfile, and verifying that the values were passed through.
=> feat: Add support for build-secrets

internal/provider/authentication_helpers.go, internal/provider/data_source_docker_registry_image.go, internal/provider/data_source_docker_registry_image_manifests.go, internal/provider/resource_docker_registry_image_funcs.go
I've found private docker registry service on hosting provider, that returns "www-authenticate" header without scope. Here is fix for that case.
=> feat: Support registries that return empty auth scope
